name: Bug Report
description: Create a report to help improve the mod functionality
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: The problem is ...
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: 1. Go to '...'
        2. Click on '....'
        3. Do '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: It should be doing ...
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Mod Version
      description: Select the version of ZoomLevel you’re running.
      options:
        - 4.5.1
        - 4.5.0
        - 4.4.0
        - 4.3.0
        - 4.2.0
        - 4.1.0
        - 4.0.1
        - 4.0.0
        - 3.2.1
        - 3.2.0
        - 3.1.0
        - 3.0.0
        - 2.3.1
        - 2.3.0
        - 2.2.0
        - 2.1.0
        - 2.0.1
        - 2.0.0
        - 1.14.0
        - 1.13.0
        - 1.3.0
        - 1.2.1
        - 1.2.0
        - 1.1.1
        - 1.1.0
        - 1.0.0
      default: 0
    validations:
      required: true
  - type: textarea
    id: settings
    attributes:
      label: Settings
      description: If applicable, add your settings of the mod here (if not using defaults, screenshots are fine for this).
    validations:
      required: true
  - type: textarea
    id: extra-attachments
    attributes:
      label: Extra Attachments
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
